package fi.utu.tech.telephonegame;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.event.EventHandler;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;

import java.io.IOException;
import fi.utu.tech.telephonegame.ui.MainViewController;

/**
 * JavaFX App
 * 
 * Do not edit this file. Älä muokkaa tätä tiedostoa.
 * 
 * This is the main class of the program. 
 * 
 */
public class App extends Application {

	private static Scene scene;
	private MainViewController controller;

	/*
	 * Don't edit any methods below this comment
	 */

	@Override
	public void start(Stage stage) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("MainView.fxml"));
		Parent root = loader.load();
		scene = new Scene(root, 800, 600);
		this.controller = loader.getController();
		stage.setScene(scene);
		stage.setTitle("Whispers");
		stage.setOnCloseRequest(new EventHandler<WindowEvent>() {
			@Override
			public void handle(WindowEvent event) {
				Platform.exit();
				System.exit(0);
			}
		});
		initialize();
		stage.show();
	}

	static void setRoot(String fxml) throws IOException {
		scene.setRoot(loadFXML(fxml));
	}

	private static Parent loadFXML(String fxml) throws IOException {
		FXMLLoader fxmlLoader = new FXMLLoader(App.class.getResource(fxml + ".fxml"));
		return fxmlLoader.load();
	}

	private void initialize() {
		GuiIO gui_io = new GuiIO(controller);
		controller.set_Gui_io(gui_io);
		MessageBroker broker = new MessageBroker(gui_io);
		gui_io.setMessageBroker(broker);
		controller.addIPs();
		broker.start();
	}

	public static void main(String[] args) {
		launch();
	}

}