package fi.utu.tech.telephonegame;

import java.util.ArrayList;

import fi.utu.tech.telephonegame.network.Network;
import fi.utu.tech.telephonegame.network.Resolver.NetworkType;
import fi.utu.tech.telephonegame.ui.MainViewController;

/**
 * Do not edit this file. Älä muokkaa tätä tiedostoa.
 * 
 * The idea of this class is to provide is abstraction between UI and business logic.
 * 
 * It is used to send data to the UI and to receive events created by user.
 * The events are passed to MessageBroker.
 * 
 */

public class GuiIO {

	private MainViewController controller;
	private MessageBroker broker;

	public GuiIO(MainViewController controller) {
		this.controller = controller;
	}

	
	/**
	 * Set the text in the Received message text area
	 * 
	 * @param text Text to be shown in "Received message" text box
	 */
	public void setReceivedMessage(String text) {
		controller.setReceivedMessage(text);
	}

	
	/**
	 * Set the text in the Refined message text area
	 * 
	 * @param text Text to be shown in "Refined message" text box
	 */
	public void setRefinedMessage(String text) {
		controller.setRefinedMessage(text);
	}
	
	/**
	 * Change the color of the color area on the GUI
	 * 
	 * @param value Color to be shown on the GUI in range 0-360
	 */
	public void setSignal(Integer value) {
		controller.setSignal(value);
	}

	
	// Method below this point are not needed in the assignment. They are only used by the templete.
	
	public void enableConnect() {
		controller.enableConnect();
	}
	
	public void setMessageBroker(MessageBroker broker) {
		this.broker = broker;
	}
	
	public void sendNewMessage(String text) {
		broker.send(text);
	}

	public void connect(NetworkType netType, boolean rootNode, String rootIPAddress) {
		broker.connect(netType, rootNode, rootIPAddress);
	}

	public ArrayList<String> getIPs() {
		return Network.getIPs();
	}
}
