package fi.utu.tech.telephonegame;

import java.io.Serializable;
import java.util.UUID;

/**
 * Do not edit this file. Älä muokkaa tätä tiedostoa.
 * 
 * This class is used as a message object in the ObjectStreams. 
 * 
 * The id value is used to identify the message and can be used to determine 
 * if the message is already seen by this node.
 * 
 * The message text is added to the String "message". 
 * 
 * The color shown in the UI is set to variable color. 
 * The value of the color is an integer between 0 and 360.
 */

public final class Message implements Serializable {

	private static final long serialVersionUID = 2L;
	private final UUID id;
	private String message;
	private Integer color;

	public Message(String message, Integer color) {
		this.message = message;
		this.color = color;
		this.id = UUID.randomUUID();
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Integer getColor() {
		return this.color;
	}

	public void setColor(Integer color) {
		this.color = color;
	}

	public UUID getId() {
		return id;
	}

}
